DELETE http://localhost:3003/api/blogs/5c6afe962db7c13cccebe0d7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhdW5vcmVwb21pZXMiLCJpZCI6IjVjNjliZDgyODJiNzU1MmY4MDQxZWI3NyIsImlhdCI6MTU1MDUxNTkyNn0.8wLd7Jy4dpvwzp0t2Zzyi8w5RYR4bQl2vBAQVuVTmZw